server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://raqecmjpyeewtj:89548cb7a16083ef902c86d2c1bb907189c34e88def20732de7ec2131ebf941e@ec2-54-145-224-156.compute-1.amazonaws.com:5432/d1uq4q65etd0md

    username : raqecmjpyeewtj
    password: 89548cb7a16083ef902c86d2c1bb907189c34e88def20732de7ec2131ebf941e
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none






